import { Router } from 'express';
import { createUser, deleteUser, listUsers, updateUser } from '../controllers/user.controller.js';
import { authenticate, allowRoles } from '../middlewares/auth.js';
import { validate } from '../middlewares/validate.js';
import { createUserSchema, updateUserSchema } from '../validators/user.validator.js';
const router = Router();
router.use(authenticate, allowRoles('ADMIN'));
router.post('/', validate(createUserSchema), createUser);
router.get('/', listUsers);
router.patch('/:id', validate(updateUserSchema), updateUser);
router.delete('/:id', deleteUser);
export default router;
